# Generated by Django 2.2.16 on 2022-06-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_added_Follow_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
